package main_test

import (
	"os"
	"path/filepath"
)

func buildLanguageConfigs(fixtureBase string) []langConfig {
	return []langConfig{
		{
			name:               "TypeScript",
			id:                 "typescript",
			binary:             "typescript-language-server",
			serverArgs:         []string{"--stdio"},
			fixture:            filepath.Join(fixtureBase, "typescript"),
			file:               filepath.Join(fixtureBase, "typescript", "src", "example.ts"),
			hoverLine:          11,
			hoverColumn:        18,
			definitionLine:     4,
			definitionColumn:   17,
			callSiteLine:       4,
			callSiteColumn:     14,
			callSiteFile:       filepath.Join(fixtureBase, "typescript", "src", "consumer.ts"),
			referenceLine:      11,
			referenceColumn:    18,
			completionLine:     7,
			completionColumn:   26,
			completionFile:     filepath.Join(fixtureBase, "typescript", "src", "consumer.ts"),
			workspaceSymbol:    "Person",
			supportsFormatting: true,
			secondFile:         filepath.Join(fixtureBase, "typescript", "src", "consumer.ts"),
			symbolName:          "Person",
			typeHierarchyLine:   11,
			typeHierarchyColumn: 18,
			highlightLine:      11,
			highlightColumn:    18,
			inlayHintEndLine:   35,
			renameSymbolLine:   11,
			renameSymbolColumn: 18,
			renameSymbolName:   "RenamedPerson",
			codeActionLine:     36,
			codeActionEndLine:  38,
		},
		{
			name:               "Python",
			id:                 "python",
			binary:             "pyright-langserver",
			serverArgs:         []string{"--stdio"},
			fixture:            filepath.Join(fixtureBase, "python"),
			file:               filepath.Join(fixtureBase, "python", "main.py"),
			hoverLine:          4,
			hoverColumn:        7,
			definitionLine:     1,
			definitionColumn:   5,
			callSiteLine:       15,
			callSiteColumn:     14,
			referenceLine:      4,
			referenceColumn:    7,
			completionLine:     14,
			completionColumn:   13,
			workspaceSymbol:    "Person",
			supportsFormatting: false,
			secondFile:         filepath.Join(fixtureBase, "python", "greeter.py"),
			symbolName:         "Person",
			highlightLine:      4,
			highlightColumn:    7,
			inlayHintEndLine:   16,
			renameSymbolLine:   4,
			renameSymbolColumn: 7,
			renameSymbolName:   "RenamedPerson",
			codeActionLine:     4,
			codeActionEndLine:  7,
		},
		{
			name:               "Go",
			id:                 "go",
			binary:             "gopls",
			serverArgs:         []string{},
			fixture:            filepath.Join(fixtureBase, "go"),
			file:               filepath.Join(fixtureBase, "go", "main.go"),
			hoverLine:          6,
			hoverColumn:        6,
			definitionLine:     16,
			definitionColumn:   6,
			callSiteLine:       23,
			callSiteColumn:     17,
			referenceLine:      6,
			referenceColumn:    6,
			completionLine:     22,
			completionColumn:   19,
			workspaceSymbol:    "Person",
			supportsFormatting: true,
			secondFile:         filepath.Join(fixtureBase, "go", "greeter.go"),
			symbolName:         "Person",
			highlightLine:      6,
			highlightColumn:    6,
			inlayHintEndLine:   20,
			renameSymbolLine:   6,
			renameSymbolColumn: 6,
			renameSymbolName:   "RenamedPerson",
			codeActionLine:     6,
			codeActionEndLine:  9,
		},
		{
			name:               "Rust",
			id:                 "rust",
			binary:             "rust-analyzer",
			serverArgs:         []string{},
			fixture:            filepath.Join(fixtureBase, "rust"),
			file:               filepath.Join(fixtureBase, "rust", "src", "main.rs"),
			hoverLine:          2,
			hoverColumn:        8,
			definitionLine:     23,
			definitionColumn:   4,
			callSiteLine:       30,
			callSiteColumn:     20,
			referenceLine:      2,
			referenceColumn:    12,
			completionLine:     28,
			completionColumn:   11,
			workspaceSymbol:    "Person",
			supportsFormatting: true,
			secondFile:         filepath.Join(fixtureBase, "rust", "src", "greeter.rs"),
			symbolName:         "Person",
			highlightLine:      2,
			highlightColumn:    8,
			inlayHintEndLine:   20,
			renameSymbolLine:   2,
			renameSymbolColumn: 8,
			renameSymbolName:   "RenamedPerson",
			codeActionLine:     2,
			codeActionEndLine:  5,
		},
		{
			name:       "Java",
			id:         "java",
			binary:     "jdtls",
			serverArgs: []string{"-data", "/tmp/jdtls-workspace-lsp-mcp-test"},
			javaHome:   os.Getenv("JAVA_HOME"),
			fixture:    filepath.Join(fixtureBase, "java"),
			file: filepath.Join(fixtureBase, "java", "src", "main", "java", "com", "example",
				"Person.java"),
			hoverLine:          6,
			hoverColumn:        14,
			definitionLine:     20,
			definitionColumn:   23,
			callSiteLine:       27,
			callSiteColumn:     28,
			referenceLine:      6,
			referenceColumn:    14,
			completionLine:     25,
			completionColumn:   16,
			workspaceSymbol:    "Person",
			supportsFormatting: true,
			secondFile: filepath.Join(fixtureBase, "java", "src", "main", "java", "com", "example",
				"Greeter.java"),
			symbolName:          "Person",
			typeHierarchyLine:   6,
			typeHierarchyColumn: 14,
			highlightLine:      6,
			highlightColumn:    14,
			inlayHintEndLine:   20,
			renameSymbolLine:   6,
			renameSymbolColumn: 14,
			renameSymbolName:   "RenamedPerson",
			codeActionLine:     6,
			codeActionEndLine:  8,
		},
		{
			name:               "C",
			id:                 "c",
			binary:             "clangd",
			serverArgs:         []string{},
			fixture:            filepath.Join(fixtureBase, "c"),
			file:               filepath.Join(fixtureBase, "c", "person.c"),
			hoverLine:          3,
			hoverColumn:        1,
			definitionLine:     10,
			definitionColumn:   5,
			callSiteLine:       16,
			callSiteColumn:     12,
			referenceLine:      3,
			referenceColumn:    1,
			completionLine:     15,
			completionColumn:   12,
			workspaceSymbol:    "Person",
			supportsFormatting: true,
			secondFile:         filepath.Join(fixtureBase, "c", "greeter.c"),
			symbolName:         "create_person",
			declarationLine:    3,
			declarationColumn:  1,
			highlightLine:      3,
			highlightColumn:    1,
			inlayHintEndLine:   15,
			renameSymbolLine:   3,
			renameSymbolColumn: 1,
			renameSymbolName:   "renamed_person",
			codeActionLine:     3,
			codeActionEndLine:  5,
		},
		{
			name:               "PHP",
			id:                 "php",
			binary:             "intelephense",
			serverArgs:         []string{"--stdio"},
			fixture:            filepath.Join(fixtureBase, "php"),
			file:               filepath.Join(fixtureBase, "php", "Person.php"),
			hoverLine:          6,
			hoverColumn:        7,
			definitionLine:     20,
			definitionColumn:   24,
			callSiteLine:       27,
			callSiteColumn:     14,
			referenceLine:      6,
			referenceColumn:    7,
			completionLine:     26,
			completionColumn:   22,
			workspaceSymbol:    "Person",
			supportsFormatting: false,
			secondFile:         filepath.Join(fixtureBase, "php", "Greeter.php"),
			symbolName:         "Person",
			highlightLine:      6,
			highlightColumn:    7,
			inlayHintEndLine:   14,
			renameSymbolLine:   6,
			renameSymbolColumn: 7,
			renameSymbolName:   "RenamedPerson",
			codeActionLine:     6,
			codeActionEndLine:  9,
		},
		{
			name:               "C++",
			id:                 "cpp",
			binary:             "clangd",
			fixture:            filepath.Join(fixtureBase, "cpp"),
			file:               filepath.Join(fixtureBase, "cpp", "person.h"),
			hoverLine:          9,
			hoverColumn:        7,
			definitionLine:     9,
			definitionColumn:   7,
			callSiteLine:       14,
			callSiteColumn:     16,
			callSiteFile:       filepath.Join(fixtureBase, "cpp", "person.cpp"),
			referenceLine:      9,
			referenceColumn:    7,
			completionLine:     10,
			completionColumn:   12,
			completionFile:     filepath.Join(fixtureBase, "cpp", "person.cpp"),
			workspaceSymbol:    "Person",
			supportsFormatting: true,
			secondFile:         filepath.Join(fixtureBase, "cpp", "greeter.cpp"),
			symbolName:         "Person",
		},
		{
			name:               "JavaScript",
			id:                 "javascript",
			binary:             "typescript-language-server",
			serverArgs:         []string{"--stdio"},
			fixture:            filepath.Join(fixtureBase, "javascript"),
			file:               filepath.Join(fixtureBase, "javascript", "src", "example.js"),
			hoverLine:          11,
			hoverColumn:        14,
			definitionLine:     11,
			definitionColumn:   14,
			callSiteLine:       7,
			callSiteColumn:     19,
			callSiteFile:       filepath.Join(fixtureBase, "javascript", "src", "consumer.js"),
			referenceLine:      11,
			referenceColumn:    14,
			completionLine:     5,
			completionColumn:   14,
			workspaceSymbol:    "Person",
			supportsFormatting: true,
			secondFile:         filepath.Join(fixtureBase, "javascript", "src", "consumer.js"),
			symbolName:         "Person",
		},
		{
			name:               "Ruby",
			id:                 "ruby",
			binary:             "solargraph",
			serverArgs:         []string{"stdio"},
			fixture:            filepath.Join(fixtureBase, "ruby"),
			file:               filepath.Join(fixtureBase, "ruby", "person.rb"),
			hoverLine:          5,
			hoverColumn:        7,
			definitionLine:     5,
			definitionColumn:   7,
			callSiteLine:       6,
			callSiteColumn:     19,
			callSiteFile:       filepath.Join(fixtureBase, "ruby", "greeter.rb"),
			referenceLine:      5,
			referenceColumn:    7,
			completionLine:     2,
			completionColumn:   6,
			workspaceSymbol:    "Person",
			supportsFormatting: true,
			secondFile:         filepath.Join(fixtureBase, "ruby", "greeter.rb"),
			symbolName:         "Person",
			highlightLine:      5,
			highlightColumn:    7,
			inlayHintEndLine:   10,
			renameSymbolLine:   2,
			renameSymbolColumn: 7,
			renameSymbolName:   "RenamedPerson",
			codeActionLine:     5,
			codeActionEndLine:  8,
		},
		{
			name:            "YAML",
			id:              "yaml",
			binary:          "yaml-language-server",
			serverArgs:      []string{"--stdio"},
			fixture:         filepath.Join(fixtureBase, "yaml"),
			file:            filepath.Join(fixtureBase, "yaml", "workflow.yml"),
			hoverLine:       2,
			hoverColumn:     1,
			definitionLine:  0,
			callSiteLine:    0,
			referenceLine:   0,
			completionLine:  24,
			completionColumn: 7,
			workspaceSymbol: "name",
			supportsFormatting: true,
		},
		{
			name:            "JSON",
			id:              "json",
			binary:          "vscode-json-language-server",
			serverArgs:      []string{"--stdio"},
			fixture:         filepath.Join(fixtureBase, "json"),
			file:            filepath.Join(fixtureBase, "json", "package.json"),
			hoverLine:       2,
			hoverColumn:     3,
			definitionLine:  0,
			callSiteLine:    0,
			referenceLine:   0,
			completionLine:  9,
			completionColumn: 5,
			workspaceSymbol: "name",
			supportsFormatting: true,
		},
		{
			name:            "Dockerfile",
			id:              "dockerfile",
			binary:          "docker-langserver",
			serverArgs:      []string{"--stdio"},
			fixture:         filepath.Join(fixtureBase, "dockerfile"),
			file:            filepath.Join(fixtureBase, "dockerfile", "Dockerfile"),
			hoverLine:       3,
			hoverColumn:     1,
			definitionLine:  0,
			callSiteLine:    0,
			referenceLine:   0,
			completionLine:  21,
			completionColumn: 1,
			workspaceSymbol: "FROM",
			supportsFormatting: false,
		},
		{
			name:               "Zig",
			id:                 "zig",
			binary:             "zls",
			serverArgs:         []string{},
			fixture:            filepath.Join(fixtureBase, "zig"),
			file:               filepath.Join(fixtureBase, "zig", "src", "person.zig"),
			hoverLine:          4,
			hoverColumn:        12,
			definitionLine:     4,
			definitionColumn:   12,
			callSiteLine:       8,
			callSiteColumn:     20,
			callSiteFile:       filepath.Join(fixtureBase, "zig", "src", "main.zig"),
			referenceLine:      4,
			referenceColumn:    12,
			completionLine:     12,
			completionColumn:   14,
			workspaceSymbol:    "Person",
			supportsFormatting: true,
			secondFile:         filepath.Join(fixtureBase, "zig", "src", "greeter.zig"),
			symbolName:         "Person",
			highlightLine:      4,
			highlightColumn:    12,
			signatureHelpLine:   8,
			signatureHelpColumn: 32,
			signatureHelpFile:   filepath.Join(fixtureBase, "zig", "src", "main.zig"),
			inlayHintEndLine:   14,
			renameSymbolLine:   4,
			renameSymbolColumn: 12,
			renameSymbolName:   "RenamedPerson",
			codeActionLine:     4,
			codeActionEndLine:  7,
		},
		{
			name:               "CSS",
			id:                 "css",
			binary:             "vscode-css-language-server",
			serverArgs:         []string{"--stdio"},
			fixture:            filepath.Join(fixtureBase, "css"),
			file:               filepath.Join(fixtureBase, "css", "styles.css"),
			hoverLine:          3,
			hoverColumn:        5,
			definitionLine:     2,
			definitionColumn:   1,
			callSiteLine:       2,
			callSiteColumn:     1,
			referenceLine:      2,
			referenceColumn:    1,
			completionLine:     3,
			completionColumn:   12,
			workspaceSymbol:    "person",
			supportsFormatting: true,
			symbolName:         "person",
			highlightLine:      2,
			highlightColumn:    1,
			inlayHintEndLine:   6,
			codeActionLine:     3,
			codeActionEndLine:  5,
		},
		{
			name:               "HTML",
			id:                 "html",
			binary:             "vscode-html-language-server",
			serverArgs:         []string{"--stdio"},
			fixture:            filepath.Join(fixtureBase, "html"),
			file:               filepath.Join(fixtureBase, "html", "index.html"),
			hoverLine:          10,
			hoverColumn:        6,
			definitionLine:     0,
			callSiteLine:       0,
			referenceLine:      0,
			completionLine:     10,
			completionColumn:   10,
			workspaceSymbol:    "div",
			supportsFormatting: true,
			symbolName:         "person",
			highlightLine:      10,
			highlightColumn:    6,
			inlayHintEndLine:   12,
			codeActionLine:     10,
			codeActionEndLine:  12,
		},
		{
			name:               "Terraform",
			id:                 "terraform",
			binary:             "terraform-ls",
			serverArgs:         []string{"serve"},
			fixture:            filepath.Join(fixtureBase, "terraform"),
			file:               filepath.Join(fixtureBase, "terraform", "main.tf"),
			hoverLine:          11,
			hoverColumn:        10,
			definitionLine:     11,
			definitionColumn:   10,
			callSiteLine:       24,
			callSiteColumn:     15,
			referenceLine:      11,
			referenceColumn:    10,
			completionLine:     12,
			completionColumn:   5,
			workspaceSymbol:    "person_name",
			supportsFormatting: true,
			secondFile:         filepath.Join(fixtureBase, "terraform", "variables.tf"),
			symbolName:         "person_name",
			highlightLine:      11,
			highlightColumn:    10,
			inlayHintEndLine:   16,
			renameSymbolLine:   11,
			renameSymbolColumn: 10,
			renameSymbolName:   "renamed_person",
			codeActionLine:     11,
			codeActionEndLine:  15,
		},
		{
			name:               "Lua",
			id:                 "lua",
			binary:             "lua-language-server",
			serverArgs:         []string{},
			fixture:            filepath.Join(fixtureBase, "lua"),
			file:               filepath.Join(fixtureBase, "lua", "person.lua"),
			hoverLine:          5,
			hoverColumn:        7,
			definitionLine:     5,
			definitionColumn:   7,
			callSiteLine:       4,
			callSiteColumn:     15,
			callSiteFile:       filepath.Join(fixtureBase, "lua", "main.lua"),
			referenceLine:      5,
			referenceColumn:    7,
			completionLine:     19,
			completionColumn:   14,
			workspaceSymbol:    "Person",
			supportsFormatting: true,
			secondFile:         filepath.Join(fixtureBase, "lua", "greeter.lua"),
			symbolName:         "Person",
			highlightLine:      5,
			highlightColumn:    7,
			inlayHintEndLine:   20,
			renameSymbolLine:   5,
			renameSymbolColumn: 7,
			renameSymbolName:   "RenamedPerson",
			codeActionLine:     5,
			codeActionEndLine:  7,
		},
		{
			name:               "Swift",
			id:                 "swift",
			binary:             "sourcekit-lsp",
			serverArgs:         []string{},
			fixture:            filepath.Join(fixtureBase, "swift"),
			file:               filepath.Join(fixtureBase, "swift", "Sources", "swift-fixture", "Person.swift"),
			hoverLine:          2,
			hoverColumn:        15,
			definitionLine:     2,
			definitionColumn:   15,
			callSiteLine:       1,
			callSiteColumn:     12,
			callSiteFile:       filepath.Join(fixtureBase, "swift", "Sources", "swift-fixture", "main.swift"),
			referenceLine:      2,
			referenceColumn:    15,
			completionLine:     10,
			completionColumn:   12,
			workspaceSymbol:    "Person",
			supportsFormatting: true,
			secondFile:         filepath.Join(fixtureBase, "swift", "Sources", "swift-fixture", "Greeter.swift"),
			symbolName:         "Person",
			highlightLine:      2,
			highlightColumn:    15,
			inlayHintEndLine:   13,
			renameSymbolLine:   2,
			renameSymbolColumn: 15,
			renameSymbolName:   "RenamedPerson",
			codeActionLine:     2,
			codeActionEndLine:  5,
		},
		{
			name:               "Scala",
			id:                 "scala",
			binary:             "metals",
			serverArgs:         []string{},
			fixture:            filepath.Join(fixtureBase, "scala"),
			file:               filepath.Join(fixtureBase, "scala", "Person.scala"),
			hoverLine:          4,
			hoverColumn:        12,
			definitionLine:     4,
			definitionColumn:   12,
			callSiteLine:       4,
			callSiteColumn:     17,
			callSiteFile:       filepath.Join(fixtureBase, "scala", "Main.scala"),
			referenceLine:      4,
			referenceColumn:    12,
			completionLine:     5,
			completionColumn:   5,
			workspaceSymbol:    "Person",
			supportsFormatting: true,
			secondFile:         filepath.Join(fixtureBase, "scala", "Greeter.scala"),
			symbolName:         "Person",
			highlightLine:      4,
			highlightColumn:    12,
			inlayHintEndLine:   5,
			renameSymbolLine:   4,
			renameSymbolColumn: 12,
			renameSymbolName:   "RenamedPerson",
			codeActionLine:     4,
			codeActionEndLine:  5,
		},
		{
			name:               "Kotlin",
			id:                 "kotlin",
			binary:             "kotlin-language-server",
			serverArgs:         []string{},
			fixture:            filepath.Join(fixtureBase, "kotlin"),
			file:               filepath.Join(fixtureBase, "kotlin", "Person.kt"),
			hoverLine:          6,
			hoverColumn:        12,
			definitionLine:     6,
			definitionColumn:   12,
			callSiteLine:       4,
			callSiteColumn:     19,
			callSiteFile:       filepath.Join(fixtureBase, "kotlin", "main.kt"),
			referenceLine:      6,
			referenceColumn:    12,
			completionLine:     7,
			completionColumn:   5,
			workspaceSymbol:    "Person",
			supportsFormatting: true,
			secondFile:         filepath.Join(fixtureBase, "kotlin", "Greeter.kt"),
			symbolName:         "Person",
			highlightLine:      6,
			highlightColumn:    12,
			inlayHintEndLine:   8,
			renameSymbolLine:   6,
			renameSymbolColumn: 12,
			renameSymbolName:   "RenamedPerson",
			codeActionLine:     6,
			codeActionEndLine:  8,
		},
		{
			name:               "CSharp",
			id:                 "csharp",
			binary:             "csharp-ls",
			serverArgs:         []string{},
			fixture:            filepath.Join(fixtureBase, "csharp"),
			file:               filepath.Join(fixtureBase, "csharp", "Person.cs"),
			hoverLine:          4,
			hoverColumn:        14,
			definitionLine:     4,
			definitionColumn:   14,
			callSiteLine:       3,
			callSiteColumn:     18,
			callSiteFile:       filepath.Join(fixtureBase, "csharp", "Program.cs"),
			referenceLine:      4,
			referenceColumn:    14,
			completionLine:     6,
			completionColumn:   20,
			workspaceSymbol:    "Person",
			supportsFormatting: true,
			secondFile:         filepath.Join(fixtureBase, "csharp", "Greeter.cs"),
			symbolName:         "Person",
			highlightLine:      4,
			highlightColumn:    14,
			inlayHintEndLine:   18,
			renameSymbolLine:   4,
			renameSymbolColumn: 14,
			renameSymbolName:   "RenamedPerson",
			codeActionLine:     4,
			codeActionEndLine:  8,
		},
		{
			name:               "Gleam",
			id:                 "gleam",
			binary:             "gleam",
			serverArgs:         []string{"lsp"},
			fixture:            filepath.Join(fixtureBase, "gleam"),
			file:               filepath.Join(fixtureBase, "gleam", "src", "person.gleam"),
			hoverLine:          5,
			hoverColumn:        8,
			definitionLine:     5,
			definitionColumn:   8,
			callSiteLine:       4,
			callSiteColumn:     18,
			callSiteFile:       filepath.Join(fixtureBase, "gleam", "src", "greeter.gleam"),
			referenceLine:      1,
			referenceColumn:    10,
			completionLine:     5,
			completionColumn:   9,
			completionFile:     filepath.Join(fixtureBase, "gleam", "src", "greeter.gleam"),
			workspaceSymbol:    "Person",
			supportsFormatting: true,
			secondFile:         filepath.Join(fixtureBase, "gleam", "src", "greeter.gleam"),
			symbolName:         "Person",
			typeDefLine:        4,
			typeDefColumn:      7,
			typeDefFile:        filepath.Join(fixtureBase, "gleam", "src", "greeter.gleam"),
			signatureHelpLine:   4,
			signatureHelpColumn: 33,
			signatureHelpFile:   filepath.Join(fixtureBase, "gleam", "src", "greeter.gleam"),
			highlightLine:      5,
			highlightColumn:    8,
			inlayHintEndLine:   18,
			renameSymbolLine:   1,
			renameSymbolColumn: 10,
			renameSymbolName:   "RenamedPerson",
			codeActionLine:     13,
			codeActionEndLine:  18,
		},
		{
			name:               "Elixir",
			id:                 "elixir",
			binary:             "elixir-ls",
			serverArgs:         []string{},
			fixture:            filepath.Join(fixtureBase, "elixir"),
			file:               filepath.Join(fixtureBase, "elixir", "lib", "person.ex"),
			hoverLine:          4,
			hoverColumn:        7,
			definitionLine:     4,
			definitionColumn:   7,
			callSiteLine:       3,
			callSiteColumn:     21,
			callSiteFile:       filepath.Join(fixtureBase, "elixir", "lib", "greeter.ex"),
			referenceLine:      1,
			referenceColumn:    11,
			completionLine:     3,
			completionColumn:   21,
			completionFile:     filepath.Join(fixtureBase, "elixir", "lib", "greeter.ex"),
			workspaceSymbol:    "Person",
			supportsFormatting: true,
			secondFile:         filepath.Join(fixtureBase, "elixir", "lib", "greeter.ex"),
			symbolName:         "Person",
			highlightLine:      1,
			highlightColumn:    11,
			inlayHintEndLine:   0, // ElixirLS does not support inlay hints
			renameSymbolLine:   0, // ElixirLS rename is unreliable
			codeActionLine:     4,
			codeActionEndLine:  6,
		},
		{
			name:               "Prisma",
			id:                 "prisma",
			binary:             "prisma-language-server",
			serverArgs:         []string{"--stdio"},
			fixture:            filepath.Join(fixtureBase, "prisma"),
			file:               filepath.Join(fixtureBase, "prisma", "schema.prisma"),
			hoverLine:          10,
			hoverColumn:        7,
			definitionLine:     10,
			definitionColumn:   7,
			callSiteLine:       21,
			callSiteColumn:     12,
			referenceLine:      10,
			referenceColumn:    7,
			completionLine:     12,
			completionColumn:   9,
			workspaceSymbol:    "Person",
			supportsFormatting: true,
			symbolName:         "Person",
			highlightLine:      10,
			highlightColumn:    7,
			inlayHintEndLine:   0, // Prisma language server does not support inlay hints
			renameSymbolLine:   10,
			renameSymbolColumn: 7,
			renameSymbolName:   "RenamedPerson",
			codeActionLine:     10,
			codeActionEndLine:  15,
		},
		{
			name:               "SQL",
			id:                 "sql",
			binary:             "sqls",
			serverArgs:         []string{"--config", filepath.Join(fixtureBase, "sql", ".sqls.yml")},
			fixture:            filepath.Join(fixtureBase, "sql"),
			file:               filepath.Join(fixtureBase, "sql", "query.sql"),
			hoverLine:          7,
			hoverColumn:        6,
			definitionLine:     7,
			definitionColumn:   6,
			callSiteLine:       8,
			callSiteColumn:     6,
			referenceLine:      7,
			referenceColumn:    6,
			completionLine:     4,
			completionColumn:   5,
			workspaceSymbol:    "person",
			supportsFormatting: false,
			symbolName:         "person",
			highlightLine:      7,
			highlightColumn:    6,
			inlayHintEndLine:   0,
			renameSymbolLine:   0,
			codeActionLine:     7,
			codeActionEndLine:  9,
		},
		{
			name:               "Clojure",
			id:                 "clojure",
			binary:             "clojure-lsp",
			serverArgs:         []string{},
			fixture:            filepath.Join(fixtureBase, "clojure"),
			file:               filepath.Join(fixtureBase, "clojure", "src", "fixture", "core.clj"),
			hoverLine:          3,
			hoverColumn:        7,
			definitionLine:     3,
			definitionColumn:   7,
			callSiteLine:       7,
			callSiteColumn:     13,
			referenceLine:      3,
			referenceColumn:    7,
			completionLine:     7,
			completionColumn:   13,
			workspaceSymbol:    "greet",
			supportsFormatting: true,
			symbolName:         "greet",
			highlightLine:      3,
			highlightColumn:    7,
			inlayHintEndLine:   0,
			renameSymbolLine:   3,
			renameSymbolColumn: 7,
			renameSymbolName:   "renamed-greet",
			codeActionLine:     3,
			codeActionEndLine:  5,
		},
		{
			name:               "Nix",
			id:                 "nix",
			binary:             "nil",
			serverArgs:         []string{},
			fixture:            filepath.Join(fixtureBase, "nix"),
			file:               filepath.Join(fixtureBase, "nix", "flake.nix"),
			hoverLine:          5,
			hoverColumn:        5,
			definitionLine:     5,
			definitionColumn:   5,
			callSiteLine:       7,
			callSiteColumn:     21,
			referenceLine:      5,
			referenceColumn:    5,
			completionLine:     7,
			completionColumn:   21,
			workspaceSymbol:    "helper",
			supportsFormatting: false,
			symbolName:         "helper",
			highlightLine:      5,
			highlightColumn:    5,
			inlayHintEndLine:   0,
			renameSymbolLine:   0,
			codeActionLine:     5,
			codeActionEndLine:  6,
		},
		{
			name:               "Dart",
			id:                 "dart",
			binary:             "dart",
			serverArgs:         []string{"language-server", "--client-id=agent-lsp"},
			fixture:            filepath.Join(fixtureBase, "dart"),
			file:               filepath.Join(fixtureBase, "dart", "lib", "fixture.dart"),
			hoverLine:          1,
			hoverColumn:        7,
			definitionLine:     2,
			definitionColumn:   10,
			callSiteLine:       4,
			callSiteColumn:     13,
			callSiteFile:       filepath.Join(fixtureBase, "dart", "lib", "caller.dart"),
			referenceLine:      1,
			referenceColumn:    7,
			completionLine:     5,
			completionColumn:   11,
			completionFile:     filepath.Join(fixtureBase, "dart", "lib", "caller.dart"),
			workspaceSymbol:    "Greeter",
			supportsFormatting: true,
			secondFile:         filepath.Join(fixtureBase, "dart", "lib", "caller.dart"),
			symbolName:         "Greeter",
			highlightLine:      1,
			highlightColumn:    7,
			inlayHintEndLine:   5,
			renameSymbolLine:   1,
			renameSymbolColumn: 7,
			renameSymbolName:   "RenamedGreeter",
			codeActionLine:     1,
			codeActionEndLine:  5,
		},
		{
			name:               "MongoDB",
			id:                 "mongodb",
			binary:             "mongodb-language-server",
			serverArgs:         []string{"--stdio"},
			fixture:            filepath.Join(fixtureBase, "mongodb"),
			file:               filepath.Join(fixtureBase, "mongodb", "query.mongodb"),
			secondFile:         filepath.Join(fixtureBase, "mongodb", "schema.mongodb"),
			hoverLine:          9,
			hoverColumn:        12,
			definitionLine:     9,
			definitionColumn:   12,
			callSiteLine:       11,
			callSiteColumn:     12,
			referenceLine:      9,
			referenceColumn:    12,
			completionLine:     9,
			completionColumn:   19,
			workspaceSymbol:    "",
			supportsFormatting: false,
			symbolName:         "find",
			highlightLine:      9,
			highlightColumn:    12,
			inlayHintEndLine:   0,
			renameSymbolLine:   0,
			codeActionLine:     9,
			codeActionEndLine:  14,
		},
	}
}

// callTool is a convenience wrapper that calls a named tool and returns the text content.
