// schema_fix.go fixes nullable array types in JSON Schemas generated by
// google/jsonschema-go. That library emits Types: ["null","array"] for Go
// slice fields because slices can be nil. Strict OpenAPI 3.0 clients (Gemini)
// reject this; they require Type: "array" (scalar string).
//
// This file provides generateFixedSchema[T] which generates a schema from a
// type parameter, walks all properties to collapse nullable arrays, and returns
// the fixed *jsonschema.Schema ready to set on mcp.Tool.InputSchema.
package main

import (
	"reflect"

	"github.com/google/jsonschema-go/jsonschema"
)

// generateFixedSchema generates a JSON Schema for type T and fixes nullable
// array properties. The returned schema is safe to assign to Tool.InputSchema
// before calling mcp.AddTool (which skips generation when InputSchema is set).
func generateFixedSchema[T any]() *jsonschema.Schema {
	rt := reflect.TypeFor[T]()
	if rt.Kind() == reflect.Pointer {
		rt = rt.Elem()
	}
	schema, err := jsonschema.ForType(rt, &jsonschema.ForOptions{})
	if err != nil {
		return nil // fall back to auto-generation
	}
	fixNullableArrays(schema)
	return schema
}

// fixNullableArrays walks a schema and replaces nullable array types with plain
// array types. The jsonschema-go library uses Types []string for multi-type
// (e.g. ["null","array"]) and Type string for single-type. The go-sdk panics
// if both are set. This function collapses Types containing "null" + one other
// type into the scalar Type field.
func fixNullableArrays(schema *jsonschema.Schema) {
	if schema == nil {
		return
	}

	// Fix this schema's type if it's a nullable union.
	if len(schema.Types) > 1 {
		var nonNull string
		for _, t := range schema.Types {
			if t != "null" {
				nonNull = t
				break
			}
		}
		if nonNull != "" {
			schema.Type = nonNull
			schema.Types = nil
		}
	}

	// Recurse into properties.
	if schema.Properties != nil {
		for _, prop := range schema.Properties {
			fixNullableArrays(prop)
		}
	}

	// Recurse into items (array element schema).
	if schema.Items != nil {
		fixNullableArrays(schema.Items)
	}

	// Recurse into additionalProperties.
	if schema.AdditionalProperties != nil {
		fixNullableArrays(schema.AdditionalProperties)
	}
}
