# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: BlackwellSystems.agent-lsp
PackageVersion: 0.1.2
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: agent-lsp.exe
    PortableCommandAlias: agent-lsp
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/blackwell-systems/agent-lsp/releases/download/v0.1.2/agent-lsp_windows_amd64.zip
    InstallerSha256: caac5bc51b78fcc68b8aea0dadf6f61d9e5dc8564d64eb3a7b88c5b71cd58cf4
  - Architecture: arm64
    InstallerUrl: https://github.com/blackwell-systems/agent-lsp/releases/download/v0.1.2/agent-lsp_windows_arm64.zip
    InstallerSha256: 9b7263953f8f376a63546647a97e7a5af669faf7882502b2e12e3338f641ad2c
ManifestType: installer
ManifestVersion: 1.6.0
